name: Build rexglue-sdk Windows x64 GDK

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  actions: write

jobs:
  build:
    uses: ./.github/workflows/_build-platform.yaml
    with:
      platform: win-amd64-gdk
      ref: ${{ github.ref }}
      publish_mode: release
    secrets: inherit
